packages:
  - 'packages/*'
  - 'examples/*'
  - 'extensions/*'

catalog:
  '@rslib/core': ^0.20.0
  '@rspress/core': ^2.0.5
  typescript: ^5.9.3
  ts-pattern: ^5.9.0
  es-toolkit: ^1.45.1
  zod: ^4.3.6
  type-fest: ^5.4.4
  vitest: ^4.1.0
